#
# Build stage
#
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn clean package

#
# Package stage
#
FROM openjdk:17-slim
COPY --from=build /build/target/*.jar /app/azure-functions.jar
EXPOSE 7071
ENTRYPOINT ["java","-jar","/app/azure-functions.jar"]
