bing:
  search:
    subscription:
      key: ${BING_SEARCH_SUBSCRIPTION_KEY:}

petstore:
  service:
    pet:
     url: ${PETSTOREPETSERVICE_URL:http://localhost:8081}
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
    order:
      url: ${PETSTOREORDERSERVICE_URL:http://localhost:8083}
  logging:
    additional-headers-to-log: ${PETSTORE_ADDITIONAL_HEADERS_TO_LOG:}
    additional-headers-to-send: ${PETSTORE_ADDITIONAL_HEADERS_TO_SEND:}
  signalR:
    negotiation-url: ${SIGNALR_NEGOTIATION_URL:}
    service-url: ${SIGNALR_SERVICE_URL:}
    key: ${SIGNALR_SERVICE_KEY:}
    update:
      fixedRate: ${SIGNALR_UPDATE_FIXEDRATE:60000}

server:
  port: ${PETSTOREAPP_SERVER_PORT:8080}

app:
  orderReservationReporting:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true

spring:
  application:
    name: petstoreapp
  thymeleaf:
    cache: false
  cache:
    cache-names: currentUsers
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
#          base-uri: https://demopetstore1q.b2clogin.com/demopetstore1q.onmicrosoft.com/
          base-uri: ${AD_B2C_BASE_URI:}
          credential:
#            client-id: e6e263ee-f47a-40ee-8d93-e06a3fd6b8ed
#            client-secret: 'OID8Q~veRZR3KFZ4us675CwuypbgagPcwzFXocD5'
            client-id: ${AD_B2C_CLIENT_ID:}
            client-secret: ${AD_B2C_CLIENT_SECRET:}
          login-flow: sign-up-or-sign-in
#          logout-success-url: https://demo-petstoreapp-eastus1.azurewebsites.net
          logout-success-url: ${AD_B2C_LOGOUT_SUCCESS_URL:}
          user-flows:
            sign-up-or-sign-in: B2C_1_signupsignin
            profile-edit: B2C_1_profileediting
            password-reset: B2C_1_passwordreset
          user-name-attribute-name: name
