springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs

server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    azure:
      cosmos:
        enabled: true
#        endpoint: https://localhost:8081
#        key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
#        endpoint: https://petstore-cosmos.documents.azure.com:443/
#        database: petstoreorder1q
#        container: order
#        key: S3tyoJ1nRdxlcjTlyf57r93APk3wpqcGAunI6drKqQg7OUT59xwAuwGQFX9xwqproVGo5ooPgXjpACDbmqe1nQ==
#        secondaryKey: AOs5tMWpscEKfjbgB8qa8NVHzk4gMRNAorxoU59b9ZZtOxK9EVissk2JoQLNqAxTKgKySadJHMeRACDb7ZgCmg==
        endpoint: ${COSMOS_ENDPOINT:}
        database: ${COSMOS_DATABASE:}
        container: ${COSMOS_CONTAINER:}
        key: ${COSMOS_KEY:}
        populate-query-metrics: true
        responseDiagnosticsEnabled: true

app:
  orderReservationReporting:
    enabled: true
    serviceBus:
#      connectionString: Endpoint=sb://petstore-bus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=iviHCiJCE522d//ZTN+E0Cd2FnJ4l6GHN+ASbHktOPM=
#      namespace: petstore-bus
#      queueName: order
      connectionString: ${ORDER_RESERVATION_CONNECTION_STRING:}
      namespace: ${ORDER_RESERVATION_NAMESPACE:}
      queueName: ${ORDER_RESERVATION_QUEUE_NAME:}

logging:
  level:
    org:
      springframework:
        context: DEBUG

debug: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  trace:
    http:
      enabled: true
  endpoint:
    httptrace:
      enabled: true
