springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs

server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    azure:
      cosmos:
        enabled: false
#        endpoint: https://localhost:8081
#        key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
        endpoint: https://petstore-cosmos.documents.azure.com:443/
        database: petstoreorder1q
        container: order
        key: S2NOalTbKqDvkneBaq9VF8fLhikGrqCGSgoxFY0spAVxFfGoExRVdJfOBOse2OhJhgVwDDfaLTQ4ACDb2cru2w==
        secondaryKey: AOs5tMWpscEKfjbgB8qa8NVHzk4gMRNAorxoU59b9ZZtOxK9EVissk2JoQLNqAxTKgKySadJHMeRACDb7ZgCmg==
        populate-query-metrics: true
        responseDiagnosticsEnabled: true

logging:
  level:
    org:
      springframework:
        context: DEBUG

debug: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  trace:
    http:
      enabled: true
  endpoint:
    httptrace:
      enabled: true
